#!/bin/bash
set -e

# =============================================================================
# PagerMon — One-Command Docker Install
# =============================================================================
# Usage:  ./install.sh
#
# This script checks/installs Docker, builds all three containers
# (postgres, pagermon, pagermon-map), starts them, and runs database
# migrations automatically on first boot.
# =============================================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
die()  { echo -e "${RED}[X]${NC} $1"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── 1. Check / install Docker ──────────────────────────────────
if ! command -v docker &>/dev/null; then
  log "Docker not found. Installing..."
  if command -v apt-get &>/dev/null; then
    apt-get update -qq && apt-get install -y -qq docker.io docker-compose
  elif command -v dnf &>/dev/null; then
    dnf install -y docker docker-compose
  elif command -v pacman &>/dev/null; then
    pacman -S --noconfirm docker docker-compose
  else
    die "Cannot detect package manager. Install Docker manually: https://docs.docker.com/engine/install/"
  fi
  systemctl start docker 2>/dev/null || true
  systemctl enable docker 2>/dev/null || true
  log "Docker installed."
fi

if ! (docker compose version &>/dev/null || docker-compose --version &>/dev/null); then
  die "docker compose is required. Run: pip install docker-compose"
fi

_docker_compose() {
  if docker compose version &>/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

# ── 2. Auto-generate .env if missing ─────────────────────────────
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  log "Generating .env with secure random values..."
  cat > "$SCRIPT_DIR/.env" <<'EOF'
# ── Auto-generated by install.sh ──────────────────────────────
# All secrets are random. Works out of the box for local testing.
# For production, edit TZ, MAP_LAT, MAP_LNG, and PUBLIC_MAP_BASE_URL.
TZ=UTC
MAP_LAT=0
MAP_LNG=0
PUBLIC_MAP_BASE_URL=http://localhost:5000
RTL_FREQ=148.5875M
PG_DATABASE=pagermon
PG_USER=pagermon
PG_PASSWORD=RANDOM
MAP_SECRET_KEY=RANDOM
PUBLIC_MAP_API_KEY=RANDOM
SERVER_PORT=3000
MAP_PORT=5000
POCSAG_MODE=POCSAG512
RTL_DEVICE=0
EOF
  # Generate actual random values
  sed -i "s/RANDOM/$(openssl rand -hex 16)/" "$SCRIPT_DIR/.env"
  sed -i "s/RANDOM/$(openssl rand -hex 32)/" "$SCRIPT_DIR/.env"
  sed -i "s/RANDOM/$(openssl rand -hex 24)/" "$SCRIPT_DIR/.env"
  log ".env created — no editing required for local testing."
  log "For production: set TZ, MAP_LAT/LNG, and PUBLIC_MAP_BASE_URL in .env"
else
  log "Using existing .env file."
fi

# Load .env variables safely
set -a
source "$SCRIPT_DIR/.env"
set +a

# ── 3. Build images ─────────────────────────────────────────────
log "Building Docker images..."
_docker_compose build

# ── 4. Start services ───────────────────────────────────────────
log "Starting PagerMon stack..."
_docker_compose up -d

# ── 5. Wait for healthy ─────────────────────────────────────────
log "Waiting for services to be healthy..."
for i in $(seq 1 60); do
  PG_OK=$(_docker_compose exec -T postgres pg_isready -U "${PG_USER:-pagermon}" 2>/dev/null || echo "no")
  if echo "$PG_OK" | grep -q "accepting"; then
    break
  fi
  sleep 2
done

for i in $(seq 1 30); do
  if curl -sf http://localhost:"${SERVER_PORT:-3000}"/health >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

# ── 6. Done ─────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  PagerMon is running!${NC}"
echo ""
echo "  PagerMon:    http://localhost:${SERVER_PORT:-3000}"
echo "  Live Map:    http://localhost:${MAP_PORT:-5000}"
echo "  Default login: admin / changeme"
echo ""
echo "  Enable Geocoder: visit Admin → Settings → Plugins → Geocoder → Enable"
echo ""
  echo "  ${YELLOW}First-time setup:${NC}"
  echo "    1. Log in and change the admin password"
  echo "    2. Admin → Location Config → add your dispatch areas"
  echo "    3. Admin → Settings → Plugins → Geocoder → Enable"
  echo "    4. Admin → Call Types → Scan for New Types"
  echo "    5. Admin → Settings → Auth → add API keys"
  echo ""
  echo "  ${YELLOW}For production:${NC}"
  echo "    Edit .env to set TZ, MAP_LAT, MAP_LNG, PUBLIC_MAP_BASE_URL"
  echo -e "${GREEN}══════════════════════════════════════════════${NC}"
