#!/bin/bash
set -e

# =============================================================================
# PagerMon — One-Command Docker Install
# =============================================================================
# Usage:  ./install.sh
#
# This script checks/installs Docker, builds all three containers
# (postgres, pagermon, pagermon-map), starts them, and runs database
# migrations automatically on first boot.
# =============================================================================

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; NC=$'\033[0m'
log()  { printf "%b\n" "${GREEN}[+]${NC} $1"; }
warn() { printf "%b\n" "${YELLOW}[!]${NC} $1"; }
die()  { printf "%b\n" "${RED}[X]${NC} $1"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── 0. Check OS compatibility ──────────────────────────────────
OS="$(uname -s)"
if [ "$OS" != "Linux" ]; then
  die "PagerMon requires Linux. Detected: $OS"
fi

if command -v apt-get &>/dev/null; then
  PKG_MGR="apt"
elif command -v dnf &>/dev/null; then
  PKG_MGR="dnf"
elif command -v pacman &>/dev/null; then
  PKG_MGR="pacman"
elif command -v zypper &>/dev/null; then
  PKG_MGR="zypper"
elif command -v apk &>/dev/null; then
  PKG_MGR="apk"
else
  PKG_MGR="unknown"
fi

if [ "$PKG_MGR" = "unknown" ]; then
  warn "Could not detect a supported package manager."
  warn "Docker will need to be installed manually if missing."
fi

# ── 1. Check / install Docker ──────────────────────────────────
if ! command -v docker &>/dev/null; then
  log "Docker not found. Installing..."
  case "$PKG_MGR" in
    apt)    apt-get update -qq && apt-get install -y -qq docker.io docker-compose ;;
    dnf)    dnf install -y docker docker-compose ;;
    pacman) pacman -S --noconfirm docker docker-compose ;;
    zypper) zypper install -y docker docker-compose ;;
    apk)    apk add --no-cache docker docker-compose ;;
    *)      die "Cannot install Docker automatically. Install manually: https://docs.docker.com/engine/install/" ;;
  esac
  log "Docker installed."
fi

# Ensure Docker is running
systemctl start docker 2>/dev/null || true
systemctl enable docker 2>/dev/null || true

if ! (docker compose version &>/dev/null || docker-compose --version &>/dev/null); then
  die "docker compose is required. Run: pip install docker-compose"
fi

_docker_compose() {
  if docker compose version &>/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

# ── 2. Auto-generate .env if missing ─────────────────────────────
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  log "Generating .env with secure random values..."
  cat > "$SCRIPT_DIR/.env" <<'EOF'
# ── Auto-generated by install.sh ──────────────────────────────
# All secrets are random. Works out of the box for local testing.
# For production, edit TZ, MAP_LAT, MAP_LNG, and PUBLIC_MAP_BASE_URL.
TZ=UTC
MAP_LAT=0
MAP_LNG=0
PUBLIC_MAP_BASE_URL=http://localhost:5000
RTL_FREQ=148.5875M
PG_DATABASE=pagermon
PG_USER=pagermon
PG_PASSWORD=__RANDOM_16__
MAP_SECRET_KEY=__RANDOM_32__
PUBLIC_MAP_API_KEY=__RANDOM_24__
SERVER_PORT=3000
MAP_PORT=5000
POCSAG_MODE=POCSAG512
RTL_DEVICE=0
EOF
  # Generate actual random values
  sed -i "s/__RANDOM_16__/$(openssl rand -hex 16)/" "$SCRIPT_DIR/.env"
  sed -i "s/__RANDOM_32__/$(openssl rand -hex 32)/" "$SCRIPT_DIR/.env"
  sed -i "s/__RANDOM_24__/$(openssl rand -hex 24)/" "$SCRIPT_DIR/.env"
  log ".env created — no editing required for local testing."
  log "For production: set TZ, MAP_LAT/LNG, and PUBLIC_MAP_BASE_URL in .env"
else
  log "Using existing .env file."
fi

# Load .env variables safely
set -a
source "$SCRIPT_DIR/.env"
set +a

# ── 3. Build images ─────────────────────────────────────────────
log "Building Docker images..."
_docker_compose build

# ── 4. Start services ───────────────────────────────────────────
log "Starting PagerMon stack..."
_docker_compose up -d

# ── 5. Wait for healthy ─────────────────────────────────────────
log "Waiting for services to be healthy..."
for i in $(seq 1 60); do
  PG_OK=$(_docker_compose exec -T postgres pg_isready -U "${PG_USER:-pagermon}" 2>/dev/null || echo "no")
  if echo "$PG_OK" | grep -q "accepting"; then
    break
  fi
  sleep 2
done

for i in $(seq 1 30); do
  if curl -sf http://localhost:"${SERVER_PORT:-3000}"/health >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

# ── 6. Done ─────────────────────────────────────────────────────
echo ""
printf "%b\n" "${GREEN}══════════════════════════════════════════════${NC}"
printf "%b\n" "${GREEN}  PagerMon is running!${NC}"
echo ""
echo "  PagerMon:    http://localhost:${SERVER_PORT:-3000}"
echo "  Live Map:    http://localhost:${MAP_PORT:-5000}"
echo "  Default login: admin / changeme"
echo ""
echo "  Enable Geocoder: visit Admin → Settings → Plugins → Geocoder → Enable"
echo ""
printf "%b\n" "  ${YELLOW}First-time setup:${NC}"
echo "    1. Log in and change the admin password"
echo "    2. Admin → Location Config → add your dispatch areas"
echo "    3. Admin → Settings → Plugins → Geocoder → Enable"
echo "    4. Admin → Call Types → Scan for New Types"
echo "    5. Admin → Settings → Auth → add API keys"
echo ""
printf "%b\n" "  ${YELLOW}For production:${NC}"
echo "    Edit .env to set TZ, MAP_LAT, MAP_LNG, PUBLIC_MAP_BASE_URL"
printf "%b\n" "${GREEN}══════════════════════════════════════════════${NC}"
