#!/bin/bash
set -e

# =============================================================================
# PagerMon — One-Command Docker Install
# =============================================================================
# Usage:  ./install.sh
#
# This script checks/installs Docker, builds all three containers
# (postgres, pagermon, pagermon-map), starts them, and runs database
# migrations automatically on first boot.
# =============================================================================

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; NC=$'\033[0m'
log()  { printf "%b\n" "${GREEN}[+]${NC} $1"; }
warn() { printf "%b\n" "${YELLOW}[!]${NC} $1"; }
die()  { printf "%b\n" "${RED}[X]${NC} $1"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
cd "$SCRIPT_DIR"

_DC_STARTED=0
_cleanup() {
  if [ "${_DC_STARTED}" = "1" ]; then
    warn "Cleaning up partial deployment..."
    _docker_compose down 2>/dev/null || true
  fi
}
trap _cleanup ERR INT TERM

# ── 0. Check OS compatibility ──────────────────────────────────
OS="$(uname -s)"
if [ "$OS" != "Linux" ]; then
  die "PagerMon requires Linux. Detected: $OS"
fi

if command -v apt-get &>/dev/null; then
  PKG_MGR="apt"
elif command -v dnf &>/dev/null; then
  PKG_MGR="dnf"
elif command -v pacman &>/dev/null; then
  PKG_MGR="pacman"
elif command -v zypper &>/dev/null; then
  PKG_MGR="zypper"
elif command -v apk &>/dev/null; then
  PKG_MGR="apk"
else
  PKG_MGR="unknown"
fi

if [ "$PKG_MGR" = "unknown" ]; then
  warn "Could not detect a supported package manager."
  warn "Docker will need to be installed manually if missing."
fi

if ! command -v curl &>/dev/null; then
  log "Installing curl (required for health checks)..."
  case "$PKG_MGR" in
    apt)    apt-get install -y -qq curl ;;
    dnf)    dnf install -y curl ;;
    pacman) pacman -S --noconfirm curl ;;
    zypper) zypper install -y curl ;;
    apk)    apk add --no-cache curl ;;
    *)      warn "Cannot install curl — health check will be skipped." ;;
  esac
fi

# ── 1. Check / install Docker ──────────────────────────────────
if ! command -v docker &>/dev/null; then
  log "Docker not found. Installing..."
  case "$PKG_MGR" in
    apt)    apt-get update -qq && apt-get install -y -qq docker.io docker-compose ;;
    dnf)    dnf install -y docker docker-compose ;;
    pacman) pacman -S --noconfirm docker docker-compose ;;
    zypper) zypper install -y docker docker-compose ;;
    apk)    apk add --no-cache docker docker-compose ;;
    *)      die "Cannot install Docker automatically. Install manually: https://docs.docker.com/engine/install/" ;;
  esac
  log "Docker installed."
fi

# Ensure Docker is running
systemctl start docker 2>/dev/null || true
systemctl enable docker 2>/dev/null || true

if ! (docker compose version &>/dev/null || docker-compose --version &>/dev/null); then
  die "docker compose is required. Run: pip install docker-compose"
fi

if ! docker ps &>/dev/null; then
  die "Cannot access Docker. Ensure you are root or in the 'docker' group. Try: sudo usermod -aG docker \$USER"
fi

_docker_compose() {
  if docker compose version &>/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

# ── 2. Auto-generate .env if missing ─────────────────────────────
if [ -d "$SCRIPT_DIR/.env" ]; then
  die ".env is a directory. Remove it:  rm -rf .env"
fi

_NEW_ENV=0
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  _NEW_ENV=1
  log "Generating .env with secure random values..."

  _gen_hex() {
    local LEN="$1"
    if command -v openssl &>/dev/null; then
      openssl rand -hex "$LEN" && return 0
    fi
    if command -v python3 &>/dev/null; then
      python3 -c "import secrets; print(secrets.token_hex($LEN))" && return 0
    fi
    if command -v xxd &>/dev/null && [ -r /dev/urandom ]; then
      dd if=/dev/urandom bs="$LEN" count=1 2>/dev/null | xxd -p && return 0
    fi
    warn "No secure random generator found — using /dev/urandom fallback"
    dd if=/dev/urandom bs="$LEN" count=1 2>/dev/null | od -A n -t x1 | tr -d ' \n'
  }

  cat > "$SCRIPT_DIR/.env" <<'EOF'
# ── Auto-generated by install.sh ──────────────────────────────
# All secrets are random. Works out of the box for local testing.
# For production, edit TZ, MAP_LAT, MAP_LNG, and PUBLIC_MAP_BASE_URL.
TZ=UTC
MAP_LAT=0
MAP_LNG=0
PUBLIC_MAP_BASE_URL=http://localhost:5000
RTL_FREQ=148.5875M
PG_DATABASE=pagermon
PG_USER=pagermon
PG_PASSWORD=__RANDOM_16__
MAP_SECRET_KEY=__RANDOM_32__
PUBLIC_MAP_API_KEY=__RANDOM_24__
SERVER_PORT=3000
MAP_PORT=5000
POCSAG_MODE=POCSAG512
RTL_DEVICE=0
EOF
  sed -i "s/__RANDOM_16__/$(_gen_hex 16)/" "$SCRIPT_DIR/.env"
  sed -i "s/__RANDOM_32__/$(_gen_hex 32)/" "$SCRIPT_DIR/.env"
  sed -i "s/__RANDOM_24__/$(_gen_hex 24)/" "$SCRIPT_DIR/.env"
  log ".env created — no editing required for local testing."
  log "For production: set TZ, MAP_LAT/LNG, and PUBLIC_MAP_BASE_URL in .env"
else
  log "Using existing .env file."
fi

# Load .env variables safely
set -a
_LOADED_ENV=1
source "$SCRIPT_DIR/.env" 2>/dev/null || _LOADED_ENV=0
set +a

if [ "$_LOADED_ENV" = "0" ]; then
  die "Failed to load .env. Check for syntax errors: unclosed quotes, spaces around '=' (use KEY=VALUE, not KEY = VALUE), or Windows CRLF line endings."
fi

# Strip carriage returns from port values (Windows CRLF)
SERVER_PORT="${SERVER_PORT//$'\r'/}"
MAP_PORT="${MAP_PORT//$'\r'/}"

# Validate port values
if ! [[ "$SERVER_PORT" =~ ^[0-9]+$ ]] || [ "$SERVER_PORT" -lt 1 ] 2>/dev/null || [ "$SERVER_PORT" -gt 65535 ] 2>/dev/null; then
  die "SERVER_PORT in .env must be a number 1-65535. Found: '$SERVER_PORT'${SERVER_PORT:+" (stray \\r? use dos2unix to fix)"}"
fi
if ! [[ "$MAP_PORT" =~ ^[0-9]+$ ]] || [ "$MAP_PORT" -lt 1 ] 2>/dev/null || [ "$MAP_PORT" -gt 65535 ] 2>/dev/null; then
  die "MAP_PORT in .env must be a number 1-65535. Found: '$MAP_PORT'${MAP_PORT:+" (stray \\r? use dos2unix to fix)"}"
fi

if [ "$SERVER_PORT" = "$MAP_PORT" ]; then
  die "SERVER_PORT and MAP_PORT must be different. Both are set to $SERVER_PORT."
fi

# Warn if new .env was generated while postgres data already exists
if [ "$_NEW_ENV" = "1" ]; then
  _PG_DIR="$SCRIPT_DIR/postgres-data"
  if [ -d "$_PG_DIR" ] && [ "$(ls -A "$_PG_DIR" 2>/dev/null)" ]; then
    warn "Existing Postgres data found in $_PG_DIR"
    warn "New .env credentials may not match the database."
    warn "To start fresh:  docker compose down --volumes && rm -rf postgres-data && rm .env && ./install.sh"
  fi
fi

# Warn if ports conflict (skip if owned by Docker)
if ss -tlnp 2>/dev/null | grep -qE ":(${SERVER_PORT:-3000}|${MAP_PORT:-5000})\b"; then
  if ! ss -tlnp 2>/dev/null | grep -E ":(${SERVER_PORT:-3000}|${MAP_PORT:-5000})\b" | grep -q docker; then
    warn "Port ${SERVER_PORT:-3000} or ${MAP_PORT:-5000} is already in use:"
    ss -tlnp 2>/dev/null | grep -E ":(${SERVER_PORT:-3000}|${MAP_PORT:-5000})\b" || true
    die "Free the ports above and re-run install.sh."
  fi
fi

# ── 3. Build images ─────────────────────────────────────────────
if [ ! -f "$SCRIPT_DIR/docker-compose.yml" ] && [ ! -f "$SCRIPT_DIR/compose.yml" ]; then
  die "No docker-compose.yml found. Are you in the right directory?"
fi
if _docker_compose ps 2>/dev/null | grep -qE "Up|Exit|running"; then
  warn "Existing PagerMon containers detected — they will be rebuilt and restarted."
  warn "To stop them first:  docker compose down"
fi
log "Building Docker images..."
_docker_compose build

# ── 4. Start services ───────────────────────────────────────────
log "Starting PagerMon stack..."
_DC_STARTED=1
_docker_compose up -d

# ── 5. Wait for healthy ─────────────────────────────────────────
log "Waiting for services to be healthy..."
_PG_READY=0
printf "  Postgres"
for i in $(seq 1 60); do
  PG_OK=$(_docker_compose exec -T postgres pg_isready -U "${PG_USER:-pagermon}" 2>/dev/null || echo "no")
  if echo "$PG_OK" | grep -q "accepting"; then
    printf " OK\n"
    _PG_READY=1
    break
  fi
  printf "."
  sleep 2
done
if [ "$_PG_READY" = "0" ]; then
  printf " TIMEOUT\n"
  warn "Postgres did not become healthy within 2 minutes."
  echo "Check logs: docker compose logs postgres"
fi

_SRV_HEALTHY=0
if ! command -v curl &>/dev/null; then
  warn "curl unavailable — skipping server health check."
else
  printf "  PagerMon server"
  for i in $(seq 1 150); do
    if curl -sf "http://localhost:${SERVER_PORT:-3000}/health" >/dev/null 2>&1; then
      printf " OK\n"
      _SRV_HEALTHY=1
      break
    fi
    printf "."
    sleep 2
  done
  if [ "$_SRV_HEALTHY" = "0" ]; then
    printf " TIMEOUT\n"
    warn "Server did not become healthy within 5 minutes."
      echo "Check logs: docker compose logs pagermon-server"
    echo ""
    echo "  Common causes:"
    echo "    - Postgres credentials mismatch (try: docker compose down --volumes && rm .env && ./install.sh)"
    echo "    - Database migration failed"
    echo "    - Server crashed on startup"
    echo ""
    _docker_compose logs pagermon-server --tail 15 2>/dev/null || true
    if [ "$_PG_READY" = "0" ]; then
      die "Deployment failed — Postgres and server both unhealthy."
    fi
    die "Deployment failed — server is unhealthy. See logs above."
  fi
fi

# ── 6. Done ─────────────────────────────────────────────────────
echo ""
printf "%b\n" "${GREEN}══════════════════════════════════════════════${NC}"
printf "%b\n" "${GREEN}  PagerMon is running!${NC}"
echo ""
echo "  PagerMon:    http://localhost:${SERVER_PORT:-3000}"
echo "  Live Map:    http://localhost:${MAP_PORT:-5000}"
echo "  Default login: admin / changeme"
echo ""
echo "  Enable Geocoder: visit Admin → Settings → Plugins → Geocoder → Enable"
echo ""
printf "%b\n" "  ${YELLOW}First-time setup:${NC}"
echo "    1. Log in and change the admin password"
echo "    2. Admin → Location Config → add your dispatch areas"
echo "    3. Admin → Settings → Plugins → Geocoder → Enable"
echo "    4. Admin → Call Types → Scan for New Types"
echo "    5. Admin → Settings → Auth → add API keys"
echo ""
printf "%b\n" "  ${YELLOW}For production:${NC}"
echo "    Edit .env to set TZ, MAP_LAT, MAP_LNG, PUBLIC_MAP_BASE_URL"
printf "%b\n" "${GREEN}══════════════════════════════════════════════${NC}"
