name: Node.js CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ develop, main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm install
      working-directory: ./server
    - run: npm run test-text
      working-directory: ./server
